E-State.UI/Controllers/AdvertController.cs
using E_State.Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace E_State.UI.Controllers
{
    public class AdvertController : Controller
    {
        IImagesService _imagesService;
        IAdvertService _advertService;

        public AdvertController(IImagesService imagesService, IAdvertService advertService)
        {
            _imagesService = imagesService;
            _advertService = advertService;
        }

        public IActionResult Details(int id)
        {
            var detail = _advertService.GetById(id);
            var img = _imagesService.List(x => x.AdvertId == id);
            ViewBag.images = img;
            return View(detail);
        }
        public IActionResult AdvertRent()
        {
            var rent = _advertService.List(x => x.Type.Situation.SituationName == "Kiralık");
            var images = _imagesService.List(x => x.Status == true);
            ViewBag.images = images;
            return View(rent);
        }
        public IActionResult AdvertSale()
        {
            var rent = _advertService.List(x => x.Type.Situation.SituationName == "Satılık");
            var images = _imagesService.List(x => x.Status == true);
            ViewBag.images = images;
            return View(rent);
        }
    }
}

E-State.UI/Views/Shared/Components/AdvertAll/Default.cshtml
@model List<Advert>

<section class="featured-properties-area section-padding-100-50">
    <div class="container">


        <div class="row">
            @foreach (var item in Model)
            {
                var c = 1;
                <!-- Single Featured Property -->

                <div class="col-12 col-md-6 col-xl-4">
                    <div class="single-featured-property mb-50 wow fadeInUp" data-wow-delay="100ms">
                        <!-- Property Thumbnail -->

                        <div class="property-thumb">
                            @foreach (var img in ViewBag.images)
                            {
                                if (img.AdvertId == item.AdvertId)
                                {   
                                    if (@c==1)
                                    {
                                        <img src="~/img/@img.ImageName" alt="">
                                    }
                                    c++;
                                }
                            }
                         

                            <div class="tag">
                                <span>@item.Type.Situation.SituationName</span>
                            </div>
                            <div class="list-price">
                                <p>@item.Price ₺</p>
                            </div>
                        </div>
                        <!-- Property Content -->
                        <div class="property-content">
                            <p class="location"><img src="~/EState/img/icons/location.png" alt="">@item.Neighbourhood.District.City.CityName - @item.Neighbourhood.District.DistrictName</p>
                            <a class="btn btn-warning" asp-action="Details" asp-controller="Advert" asp-route-id="@item.AdvertId">Detaya Git</a>
                            <p>@item.AdvertTitle</p>
                            <div class="property-meta-data d-flex align-items-end justify-content-between">
                                <div class="new-tag">
                                    <img src="~/EState/img/icons/new.png" alt="">
                                </div>
                                <div class="bathroom">
                                    <img src="~/EState/img/icons/bathtub.png" alt="">
                                    <span>@item.BathroomNumbers</span>
                                </div>
                                <div class="garage">
                                    <img src="~/EState/img/icons/garage.png" alt="">
                                    <span>@item.Garage</span>
                                </div>
                                <div class="space">
                                    <img src="~/EState/img/icons/space.png" alt="">
                                    <span>@item.Area m <sub>2</sub> </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>